Bug Fix and Biber Support
cherti/ibutex pull request #2
Opened 2018-03-22 14:38 UTC by Felix5721

Fixed bug that prevented using multiple tex files for building different document documents in same source directory.

Added a command line flag to switch to using biber instead of bibtex.

2018-03-23 18:46 UTC, cherti requested changes

2018-03-23 18:46 UTC, cherti commented on ibutex.py
> +parser.add_argument('--biber', action="store_true", dest='biber', default=False, help='use biber instead of bibtex')
We will not go down this rabbithole of madness. Move line 6 (`bibtexbase`) into a commandline flag `-b/--bibcmd` and let it default to `bibtex`. I intend to do similar things for a `-l/--latexcmd` to get rid of `latexbase` in line 5. We will not start to add cli-flags for single programs, madness of unmaintainable code lies there....

(and make sure you commit with `--amend` to ensure that we stick with two commits here)

2018-03-25 20:17 UTC, Felix5721 commented
Changed cmd parameter as requested.

2018-03-25 20:42 UTC, cherti requested changes

2018-03-25 20:42 UTC, cherti commented on ibutex.py
> +parser.add_argument('-b', '--bibcmd', type=str, dest='bibcmd', default="bibtex", help='use biber instead of bibtex')
The helpstring still needs to be corrected. ;)

2018-03-25 20:46 UTC, cherti commented
Commitmessage still needs to be corrected alongside, after that we can merge

2018-03-25 22:06 UTC, Felix5721 commented
commit updated

2018-03-29 20:27 UTC, cherti approved these changes

2018-03-29 20:28 UTC, cherti commented
lgtm, thanks!

2018-03-29 20:28 UTC, merged